# Generated by Django 5.0.3 on 2024-03-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='profiel',
            new_name='profile',
        ),
    ]
